### ISSUE TITLE
add ability to set env properties

### ISSUE THREAD

**Issue by gabrielcsapo** [gabrielcsapo/build.sh#1]
being able to override env variables statically could allow more use cases. 

```yaml
env:
   - FOO=bar
output: ./docs/example
pipeline:
  install:
    - npm --version
    - node --version
    - npm:
      - npm install
      - ls -lh node_modules
  lint:
    - npm run lint
  coverage:
    - npm run coverage
  test:
    - npm test
```
