### ISSUE TITLE
be able to run specific steps in the pipeline

### ISSUE THREAD

**Issue by gabrielcsapo** [gabrielcsapo/build.sh#2]
`build install` will just run the install step of the pipeline

```yaml
output: ./docs/example
pipeline:
  install:
    - npm --version
    - node --version
    - npm:
      - npm install
      - ls -lh node_modules
  lint:
    - npm run lint
  coverage:
    - npm run coverage
  test:
    - npm test
```
